### ISSUE TITLE
Production Tasks

### ISSUE THREAD

**Issue by matikin9** [hackforla/ndoch-2017#10]
- [x] Lock down location - #1 
  - [x] A/V, electrical - if location doesn't provide, reach out to Lilly
- [x] Create event page - #7 
- [x] Send out communications about event - #5 
- [x] Define volunteer needs - #6 
- [ ] Food/Drink - decide and order (give Carla a headcount)
- [ ] Define day of schedule - #4 
- [ ] Bring swag from LACI.
- [ ] Reach out to and schedule volunteers - #6 
- [ ] laptop
- [ ] cable hookup with the right port to connect the laptop to the projector
- [ ] extension cords (to power the laptop/projector, to connect to power strips) - Nina will pick up some spares
- [ ] basic presentation to have in background, sponsor logos

**Comment by carlacasilli** [comment]
Hey, now that we've locked down CCF's JPCC for the event, please provide the specific asks for the AV. Want to see what we can cover and what we might still need to work on.

**Comment by matikin9** [comment]
@carlacasilli Starting a list:

* [x] screen
* [ ] laptop
* [ ] cable hookup with the right port to connect the laptop to the projector
* [ ] extension cords (to power the laptop/projector, to connect to power strips) - Nina will pick up some spares
* [x] microphone & speakers
* [x] power strips for attendees

**Comment by carlacasilli** [comment]
The room is set up for AV (3 large screens) + mic + speakers
Folks must bring their own laptop but we have a pc that is connected directly to the screens
For simplicity's sake, presentations should be on a thumb drive
Mac folks should bring their own HDMI-to-whatever dongles / adapters
Power strips are available but the number is maybe 3? 
Bring extension cords if desired to use with power strips.

(updated 09.13.17)

**Comment by matikin9** [comment]
Thanks for the update @carlacasilli !  How close are the outlets to the seating area?  Do you have a rough diagram of what the room layout will look like?

**Comment by AnthonyRollins** [comment]
@matikin9 let's bring our old **Hack for LA** stickers, Code for America stuff and that should be suffice.
